# =========================
# SERVER
# =========================
server:
  port: 8080

# =========================
# SPRING CONFIG
# =========================
spring:

  application:
    name: api-gateway

  cloud:

    gateway:

      routes:

        # =========================
        # AUTH SERVICE - AUTH
        # =========================
        - id: auth-service-auth

          uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}

          predicates:
            - Path=/api/auth/**

          filters:
            - StripPrefix=0

        # =========================
        # AUTH SERVICE - ADMIN
        # =========================
        - id: auth-service-admin

          uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}

          predicates:
            - Path=/api/admin/**

          filters:
            - StripPrefix=0

        # =========================
        # AUTH SERVICE - USERS
        # =========================
        - id: auth-service-users

          uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}

          predicates:
            - Path=/api/users/**

          filters:
            - StripPrefix=0

        # =========================
        # STAGE SERVICE API
        # =========================
        - id: stage-service

          uri: http://${STAGE_SERVICE_HOST:localhost}:${STAGE_SERVICE_PORT:8082}

          predicates:
            - Path=/api/offres/**,/api/demandes/**,/api/livrables/**,/api/commentaires/**,/api/soutenances/**,/api/encadrants/**

          filters:
            - StripPrefix=0

        # =========================
        # FILE STORAGE API
        # =========================
        - id: stage-files

          uri: http://${STAGE_SERVICE_HOST:localhost}:${STAGE_SERVICE_PORT:8082}

          predicates:
            - Path=/api/files/**

          filters:
            - StripPrefix=0

# =========================
# ACTUATOR & PROMETHEUS
# =========================
management:

  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: api-gateway