apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# =============================================
# NAMESPACE
# =============================================
namespace: logging

# =============================================
# ORDRE DE DÉPLOIEMENT
# Kustomize applique dans cet ordre
# =============================================
resources:
  - namespace-logging.yaml   # 1. Namespace + Secret
  - pv-pvc.yaml              # 2. PV + PVC (avant les pods !)
  - opensearch.yaml          # 3. Pod OpenSearch
  - dashboards.yaml          # 4. Pod Dashboards
  - fluentbit.yaml           # 5. DaemonSet Fluent Bit + RBAC

# =============================================
# LABELS COMMUNS appliqués à toutes les ressources
# =============================================
commonLabels:
  project: gestion-de-stage
  component: logging
  managed-by: kustomize