apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# =============================================
# NAMESPACE
# =============================================
namespace: logging

# =============================================
# ORDRE DE DÉPLOIEMENT
# Kustomize applique dans cet ordre
# =============================================
resources:
  - namespace-logging.yml   # 1. Namespace + Secret
  -  pvc-pv.yml              # 2. PV + PVC (avant les pods !)
  - opensearch.yml          # 3. Pod OpenSearch
  - dashboards.yml          # 4. Pod Dashboards
  - fluentbit.yml           # 5. DaemonSet Fluent Bit + RBAC

# =============================================
# LABELS COMMUNS appliqués à toutes les ressources
# =============================================
commonLabels:
  project: gestion-de-stage
  component: logging
  managed-by: kustomize