---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging

---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
  namespace: logging
type: Opaque
stringData:
  username: admin
  password: Admin@Logs2024