---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging

---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
  namespace: logging
  annotations:
    managed-by: "jenkins-pipeline"
type: Opaque
data:
  username: cGxhY2Vob2xkZXI=
  password: cGxhY2Vob2xkZXI=