---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  namespace: logging
data:
  opensearch.yml: |
    cluster.name: gestion-de-stage-logs
    network.host: 0.0.0.0
    discovery.type: single-node
    bootstrap.memory_lock: false
    plugins.security.disabled: true
    node.max_local_storage_nodes: 1
    indices.fielddata.cache.size: 20%

---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: logging
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: logging
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      initContainers:
        - name: fix-vm-map
          image: busybox:1.35
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true

        - name: fix-permissions
          image: busybox:1.35
          command: ["chown", "-R", "1000:1000", "/usr/share/opensearch/data"]
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data

      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.13.0
          ports:
            - containerPort: 9200
              name: http
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: discovery.type
              value: single-node
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
            - name: config
              mountPath: /usr/share/opensearch/config/opensearch.yml
              subPath: opensearch.yml
          resources:
            requests:
              memory: "768Mi"
              cpu: "250m"
            limits:
              memory: "1536Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200