apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: gestion-projet
data:
  application.yml: |
    server:
      port: 8080

    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          routes:
            - id: auth-service-auth
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=0

            - id: auth-service-admin
              uri: http://auth-service:8081
              predicates:
                - Path=/api/admin/**
              filters:
                - StripPrefix=0

            - id: auth-service-users
              uri: http://auth-service:8081
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=0

            - id: stage-service
              uri: http://stage-service:8082
              predicates:
                - Path=/api/offres/**,/api/demandes/**,/api/livrables/**,/api/commentaires/**,/api/soutenances/**,/api/encadrants/**
              filters:
                - StripPrefix=0

            - id: stage-files
              uri: http://stage-service:8082
              predicates:
                - Path=/api/files/**
              filters:
                - StripPrefix=0

    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus
      endpoint:
        health:
          show-details: always
      metrics:
        tags:
          application: gateway-service

    logging:
      level:
        org.springframework.cloud.gateway: INFO
        reactor.netty: WARN