apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gestion-projet

resources:
  - configmap.yml
  - gateway-deployment.yml
  - gateway-service.yml

# ← ajouter ceci
images:
  - name: nour292/api-gateway
    newTag: "105"